apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-oklq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-oklq
    app.kubernetes.io/part-of: test-app-knzw
  name: test-component-oklq
  namespace: build-templates-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-oklq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-oklq
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images@sha256:e6a47e5d17698d28852f65fbad89cd5e84857986b9660aa7d9edcee0eed4bcc4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
